services:
  composer:
    image: composer:2
    volumes:
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
    working_dir: /app
    command: ["composer", install]

  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: test
    volumes:
      - ./app:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./certs/fullchain1.pem:/etc/ssl/certs/origin_certificate.pem
      - ./certs/privkey1.pem:/etc/ssl/private/origin_private.key
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_NAME=${BOT_NAME}
      - NASA_API_KEY=${NASA_API_KEY}
